/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cookiesales;

/**
 *Creates a user interface that sells cookies to the user when they click on the cookie they want
 * @author wtadlock18
 */
public class CookieSales extends javax.swing.JFrame {
    Store store= new Store();
    /**
     * Creates new form CookieSales
     */
    public CookieSales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThinMint = new javax.swing.JButton();
        Samoa = new javax.swing.JButton();
        Tagalong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        ThinSold = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TagSold = new javax.swing.JLabel();
        SamSold = new javax.swing.JLabel();
        Revenue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ThinMint.setIcon(new javax.swing.ImageIcon("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\HW02\\CookieSales\\src\\cookiesales\\ThinMints.jpg")); // NOI18N
        ThinMint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThinMintActionPerformed(evt);
            }
        });

        Samoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\HW02\\CookieSales\\src\\cookiesales\\Somoa.jpg")); // NOI18N
        Samoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamoaActionPerformed(evt);
            }
        });

        Tagalong.setIcon(new javax.swing.ImageIcon("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\HW02\\CookieSales\\src\\cookiesales\\tagalongs.gif")); // NOI18N
        Tagalong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TagalongActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\HW02\\CookieSales\\src\\cookiesales\\girl-scout-logo.jpg")); // NOI18N
        jLabel1.setToolTipText("");

        Message.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Message.setForeground(new java.awt.Color(0, 102, 102));
        Message.setText("  ");

        ThinSold.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        ThinSold.setForeground(new java.awt.Color(0, 204, 51));
        ThinSold.setText("0 Sold");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Select the cookie you would like to buy");

        TagSold.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        TagSold.setForeground(new java.awt.Color(255, 0, 0));
        TagSold.setText("0 Sold");

        SamSold.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        SamSold.setForeground(new java.awt.Color(102, 0, 102));
        SamSold.setText("0 Sold");

        Revenue.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Revenue.setForeground(new java.awt.Color(0, 102, 102));
        Revenue.setText("Total money raised: $0 ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("How many would you like?");

        Amount.setBackground(new java.awt.Color(240, 240, 240));
        Amount.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Amount.setText("1");
        Amount.setToolTipText("");
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jLabel2.setText("Images From Girl Scouts of America");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40))
                                        .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ThinMint, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ThinSold, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SamSold, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Samoa, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tagalong, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TagSold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(Revenue)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Message)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tagalong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThinMint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Samoa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThinSold)
                    .addComponent(TagSold)
                    .addComponent(SamSold))
                .addGap(33, 33, 33)
                .addComponent(Revenue)
                .addGap(42, 42, 42)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Sells an entered amount of Thin mints 
 * @param evt A click on the Thin Mint button
 */
    private void ThinMintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThinMintActionPerformed
        // TODO add your handling code here:
        store.buy(1,Integer.parseInt(Amount.getText()));
        Message.setText("Sold. Enjoy your Thin Mints!");
        ThinSold.setText(""+store.getAmountOf(1)+" Sold");
        Revenue.setText("Total money raised: $"+store.getRevenue());
    }//GEN-LAST:event_ThinMintActionPerformed
/**
 * Sells an entered amount of Thin mints 
 * @param evt A click on the Thin Mint button
 */
    private void SamoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamoaActionPerformed
        // TODO add your handling code here:
        store.buy(2,Integer.parseInt(Amount.getText()));
        Message.setText("Sold. Enjoy your Samoas!");
        SamSold.setText(""+store.getAmountOf(2)+" Sold");
        Revenue.setText("Total money raised: $"+store.getRevenue());
    }//GEN-LAST:event_SamoaActionPerformed
/**
 * Sells an entered amount of Thin mints 
 * @param evt A click on the Thin Mint button
 */
    private void TagalongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TagalongActionPerformed
        // TODO add your handling code here:
        store.buy(3,Integer.parseInt(Amount.getText()));
        Message.setText("Sold. Enjoy your Tagalongs!");
        TagSold.setText(""+store.getAmountOf(3)+" Sold");
        Revenue.setText("Total money raised: $"+store.getRevenue());
    }//GEN-LAST:event_TagalongActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    /**
     * Runs the user interface
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookieSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookieSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookieSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookieSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CookieSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Revenue;
    private javax.swing.JLabel SamSold;
    private javax.swing.JButton Samoa;
    private javax.swing.JLabel TagSold;
    private javax.swing.JButton Tagalong;
    private javax.swing.JButton ThinMint;
    private javax.swing.JLabel ThinSold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
