/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantreviewer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author dub10_000
 */
public class RestaurantReviewer extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantReviewer
     */
    private int star;
    private final ImageIcon s1=new ImageIcon("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\HW04\\RestaurantReviewer\\src\\restaurantreviewer\\Star1.png");
    private final ImageIcon s2=new ImageIcon("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\HW04\\RestaurantReviewer\\src\\restaurantreviewer\\Star2.png");
    public RestaurantReviewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reviewer = new javax.swing.JFrame();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rName = new javax.swing.JLabel();
        rGetName = new javax.swing.JTextField();
        lName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addNew = new javax.swing.JButton();
        oldr = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JButton();

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantreviewer/Star1.png"))); // NOI18N
        star1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star1MouseClicked(evt);
            }
        });

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantreviewer/Star2.png"))); // NOI18N

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantreviewer/Star2.png"))); // NOI18N

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantreviewer/Star2.png"))); // NOI18N

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantreviewer/Star2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("Beautiful Review");

        rName.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        rName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rName.setText(" ");

        rGetName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rGetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGetNameActionPerformed(evt);
            }
        });
        rGetName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rGetNameKeyReleased(evt);
            }
        });

        lName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lName.setText("Restaurant Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Star Rating:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Review");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReviewerLayout = new javax.swing.GroupLayout(Reviewer.getContentPane());
        Reviewer.getContentPane().setLayout(ReviewerLayout);
        ReviewerLayout.setHorizontalGroup(
            ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReviewerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(122, 122, 122))
            .addGroup(ReviewerLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(rName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
            .addGroup(ReviewerLayout.createSequentialGroup()
                .addGroup(ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReviewerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lName)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReviewerLayout.createSequentialGroup()
                                .addComponent(star1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(star2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(star3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(star4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(star5))
                            .addComponent(rGetName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReviewerLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReviewerLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel6))
                    .addGroup(ReviewerLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(Submit)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        ReviewerLayout.setVerticalGroup(
            ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewerLayout.createSequentialGroup()
                .addGroup(ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReviewerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rGetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lName))
                        .addGap(18, 18, 18)
                        .addGroup(ReviewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(star1)
                            .addComponent(star2)
                            .addComponent(star3)
                            .addComponent(star4)
                            .addComponent(star5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ReviewerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit)
                .addGap(7, 7, 7))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("The Beautiful Restaurant Reviewer");

        addNew.setText("Add Review To A New Restaurant");
        addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewActionPerformed(evt);
            }
        });

        oldr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Saga", "McDonalds", "Wendy's", "SubWay" }));

        jLabel2.setText("Current Restaurants:");

        add.setText("Add Review To An Existing Restaurant");
        add.setActionCommand("Add Review To An Existing Restaurant");
        add.setName(""); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(oldr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addNew)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(addNew)
                .addGap(0, 169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewActionPerformed
        // TODO add your handling code here:
        rName.setText("");
        Reviewer.setVisible(true);
        Reviewer.setSize(Reviewer.getPreferredSize());
    }//GEN-LAST:event_addNewActionPerformed

    private void rGetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rGetNameActionPerformed

    private void star1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseClicked
        // TODO add your handling code here:
        if(star1.getIcon().equals(s1)){
            star1.setIcon(s2);
        }else{
            star1.setIcon(s1);
        }
    }//GEN-LAST:event_star1MouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(((String)oldr.getSelectedItem()).equals("Select")){
            
        }
        rName.setText((String)oldr.getSelectedItem());
        Reviewer.setVisible(true);
        Reviewer.setSize(Reviewer.getPreferredSize());
    }//GEN-LAST:event_addActionPerformed

    private void rGetNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rGetNameKeyReleased
        // TODO add your handling code here:
        rName.setText(rGetName.getText());
    }//GEN-LAST:event_rGetNameKeyReleased

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        Reviewer.setVisible(false);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantReviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantReviewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Reviewer;
    private javax.swing.JButton Submit;
    private javax.swing.JButton add;
    private javax.swing.JButton addNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lName;
    private javax.swing.JComboBox oldr;
    private javax.swing.JTextField rGetName;
    private javax.swing.JLabel rName;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}
