/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package underover;

import java.awt.*;
import java.io.*;

import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *The GUI where everything happens with this dice game
 * @author dub10_000
 */
public class UnderOver extends javax.swing.JFrame {

    /**
     * Creates new form UnderOver
     */
    private HashMap<String,Integer> users=new HashMap<>();
    String currentUser="";
    public UnderOver() {
        initComponents();
    }
    /**
     * Reads all users currently in the system and updates them in the map
     */
    public void ReadUsers(){
        File f=new File("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\Exam1\\users.txt");
        String n;
        int m;
       
        String line;
        try{ 
            BufferedReader rdr=new BufferedReader(new FileReader(f));
            while((line=rdr.readLine())!=null){
                n=line;
                if((line=rdr.readLine())!=null){
                    m=Integer.parseInt(line);
                    users.put(n, m);
                }
                
            }
            rdr.close();//always remember to close the file
        }
        catch(Exception ex){
            System.out.println("Something Went Horibly Wrong");
        }
    }
    /**
     * Updates every user in the system if the values changed
     */
    public void UpdateUsers(){
        File f=new File("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\Exam1\\users.txt");
        File t=new File("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\Exam1\\temp.txt");
        String n;
        String m;
        ArrayList<String> lines=new ArrayList();
        String line;
        try{ 
            BufferedReader rdr=new BufferedReader(new FileReader(f));
            BufferedWriter wrtr=new BufferedWriter(new FileWriter(t));
            while((line=rdr.readLine())!=null){
                n=line;
                wrtr.write(n);
                wrtr.newLine();
                if((line=rdr.readLine())!=null){
                    m=String.format("%d",users.get(n));
                    wrtr.write(m);
                    wrtr.newLine();
                }
            }
            rdr.close();//always remember to close the file
            wrtr.close();//Always remember to close the file
            BufferedReader rdr2=new BufferedReader(new FileReader(t));
            BufferedWriter wrtr2=new BufferedWriter(new FileWriter(f));
            while((line=rdr2.readLine())!=null){
                n=line;
                wrtr2.write(n);
                wrtr2.newLine();
                if((line=rdr2.readLine())!=null){
                    m=line;
                    wrtr2.write(m);
                    wrtr2.newLine();
                }
            }
            rdr2.close();//always remember to close the file
            wrtr2.close();//Always remember to close the file
        }
        catch(Exception ex){
            System.out.println("Something Went Horibly Wrong");
        }
    }
    /**
     * The dice roll
     * @return The sum of the dice
     */
    public int Roll(){
            DiceRoll dr=new DiceRoll();
            int first=dr.getFirst();
            int second=dr.getSecond();
            int sum=dr.getSum();
            String i1 = String.format("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\Exam1\\dice%d.png",first);
            String i2 = String.format("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\Exam1\\dice%d.png",second);
            die1.setIcon( new ImageIcon(i1) );
            die2.setIcon( new ImageIcon(i2) );
            String r=String.format("We rolled. The sum of %s and %s is %s",first,second,sum);
            Results.setText(r);
            return sum;
    }
    /**
     * The over 7 bet
     * @return true if the sum is over 7, false otherwise
     */
    public boolean betOver7(){
        return Roll()>7;
    }
    /**
     * The under 7 bet
     * @return true if the sum is under 7, false otherwise
     */
    public boolean betUnder7(){
        return Roll()<7;
    }
    /**
     * The 7 bet
     * @return true if the sum is 7, false otherwise
     */
    public boolean bet7(){
        return Roll()==7;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BetType = new javax.swing.JComboBox();
        Login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NameDisplay = new javax.swing.JLabel();
        Money = new javax.swing.JLabel();
        Bet = new javax.swing.JTextField();
        Descriptor = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        die1 = new javax.swing.JLabel();
        die2 = new javax.swing.JLabel();
        PlaceBet = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Info = new javax.swing.JLabel();
        Results = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BetType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose", "Under 7", "Over 7", "7" }));
        BetType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Login Name:");

        NameDisplay.setText("Please Login");

        Money.setText("Current Money: ");

        Bet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetActionPerformed(evt);
            }
        });

        Descriptor.setText("Please Choose Which Bet You will place");

        d1.setToolTipText("");

        die1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/underover/dice3.png"))); // NOI18N

        die2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/underover/dice4.png"))); // NOI18N

        PlaceBet.setText("Roll The Dice");
        PlaceBet.setToolTipText("");
        PlaceBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceBetActionPerformed(evt);
            }
        });

        Submit.setText("Login");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Info.setText("Place your bet and Roll the Dice");

        jLabel2.setText("Your bet: $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(die1)
                                .addGap(69, 69, 69)
                                .addComponent(die2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(d1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Submit)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Money)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Descriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PlaceBet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameDisplay)
                .addGap(14, 14, 14)
                .addComponent(Money)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceBet)
                    .addComponent(Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(d1)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(die1)
                            .addComponent(die2))
                        .addGap(28, 28, 28)
                        .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BetActionPerformed
/**
 * Checks to see if the user can place a bet. If they can't then it exits.
 * @param evt click on the make bet button
 */
    private void PlaceBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceBetActionPerformed
        // TODO add your handling code here:
        try{int b=0;
        if(currentUser.length()==0){
            Info.setText("Please Log in");
            return;
        }
        if(users.get(currentUser)==0){
            Info.setText("We're sorry. You are out of funds. Please get out of here");
            return;
        }
        if(Bet.getText().length()>0&&currentUser.length()>0){
            b=Integer.parseInt(Bet.getText());
            if(b>users.get(currentUser)){
                Info.setText("You don't have that much money");
                return;
            }
        
            if(BetType.getSelectedItem().equals("Choose")){
                Info.setText("Please Choose Which Bet You will place");
            }
            if(BetType.getSelectedItem().equals("Under 7")){
                if(betUnder7()){
                    Results.setText(Results.getText()+". YOU WIN!!");
                    users.put(currentUser, users.get(currentUser)+b);
                }else{
                    Results.setText(Results.getText()+". YOU LOSE!!");
                    users.put(currentUser, users.get(currentUser)-b);
                }
               
            }
            if(BetType.getSelectedItem().equals("Over 7")){
                if(betOver7()){
                    Results.setText(Results.getText()+". YOU WIN!!");
                    users.put(currentUser, users.get(currentUser)+b);
                }else{
                    Results.setText(Results.getText()+". YOU LOSE!!");
                    users.put(currentUser, users.get(currentUser)-b);
                }
            }
            if(BetType.getSelectedItem().equals("7")){
                if(bet7()){
                    Results.setText(Results.getText()+". YOU WIN!!");
                    users.put(currentUser, users.get(currentUser)+(4*b));
                }else{
                    Results.setText(Results.getText()+". YOU LOSE!!");
                    users.put(currentUser, users.get(currentUser)-(4*b));
                }
            }
            Money.setText("Current Money: $"+users.get(currentUser));
            UpdateUsers();
        }else{
            Info.setText("Please enter the amount of money you are betting");
        }
        }catch(Exception ex){
            System.out.println("you broke it. Enter a number");
        }
    }//GEN-LAST:event_PlaceBetActionPerformed
/**
 * Loads the current user. 
 * @param evt click on the login button
 */
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        ReadUsers();//Reads the file of users and stores everything into the map users
        File f=new File("C:\\Users\\dub10_000\\Documents\\Whitworth\\JavaAppDev\\CS372\\Exam1\\users.txt");
        String name=Login.getText();
        int m=500;//the amount of money the user has to 500 as a default
        if(name.length()>0){
            try{
               Set<String> names=  users.keySet();//a set of all of the users names
               if(names.contains(name)){//if the map has a the user in it
                    NameDisplay.setText("Welcome Back "+name);
                    m=users.get(name);
                    Money.setText("Current Money: $"+m);
               } 
                else{//creates a new user
                    BufferedWriter wrtr=new BufferedWriter(new FileWriter(f,true));
                    wrtr.write(name);
                    NameDisplay.setText("Welcome "+name);
                    wrtr.newLine();
                    wrtr.write("500");
                     Money.setText("Current Money: $"+m);
                    wrtr.newLine();
                    wrtr.close();//Always remember to close the file
                }
                users.put(name, m);
                currentUser=name;
            }
            catch(Exception ex){
            System.out.println("Something Went Horribly Wrong.");
            }
        }else{
            NameDisplay.setText("Invalid name");
        }
        
    }//GEN-LAST:event_SubmitActionPerformed
/**
 * Describes the type of bets
 * @param evt when a new bet is selected
 */
    private void BetTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetTypeActionPerformed
        // TODO add your handling code here:
        if(BetType.getSelectedItem().equals("Choose")){
            Descriptor.setText("Please Choose Which Bet You will place");
        }
        if(BetType.getSelectedItem().equals("Under 7")){
            Descriptor.setText("If the sum of the two dice is under 7 you are paid your bet");
        }
        if(BetType.getSelectedItem().equals("Over 7")){
            Descriptor.setText("If the sum of the two dice is above 7 you are paid your bet");
        }
        if(BetType.getSelectedItem().equals("7")){
            Descriptor.setText("If the sum of the two dice is 7 you are paid four times your bet");
        }
    }//GEN-LAST:event_BetTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnderOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bet;
    private javax.swing.JComboBox BetType;
    private javax.swing.JLabel Descriptor;
    private javax.swing.JLabel Info;
    private javax.swing.JTextField Login;
    private javax.swing.JLabel Money;
    private javax.swing.JLabel NameDisplay;
    private javax.swing.JButton PlaceBet;
    private javax.swing.JLabel Results;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel die1;
    private javax.swing.JLabel die2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
